image: docker:latest
services:
  - docker:18.09.7-dind
stages:
  - build
  - deploy
  
variables:
  DOCKER_HOST: tcp://docker:2375
  REGISTRY_NAME: registry.gitlab.com/xxxx/gcp deployment:$CI_COMMIT_SHORT_SHA
  pass1: $DOCKER_PASS
  user1: $CI_REGISTRY_USER

build:
  stage: build
  tags: ["demo2"]
  script:
    - echo "$DOCKER_PASS" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    # Build and tag image for Gitlab registries
    - docker build -t $REGISTRY_NAME .
    # Push image 
    - docker push $REGISTRY_NAME
    
deploy:
  stage: deploy
  tags: ["demo1"] #shell-executor
  variables:
    APP_NAME: flask-python
    SERVICE_ACCOUNT: XXXXX
script:
    - export hello1=registry.gitlab.com/xxxx/gcp-deployment:$CI_COMMIT_SHORT_SHA 
    - echo $hello1
    - echo $SERVICE_ACCOUNT | base64 -d > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud container clusters get-credentials gitlabci --zone us-central1-c --project searce-playground-automation
    - kubectl get all
    - helm upgrade ${APP_NAME} --install .

