apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python
  name: flask-python   
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          ports:
            - name: http
              containerPort: 5000
      imagePullSecrets:
      - name: "{{ .Values.image.secret.name }}"